// End-to-end with headless Chrome's virtual authenticator over CDP, against a running server (same-origin path):
// create an account, sign the delegation, upvote, comment, retract, reload, sign out, sign in again, then verify a record offline.
// Usage: node scripts/e2e.mjs [http://localhost:8100]
import WebSocket from "ws"; import { spawn } from "node:child_process"; import { existsSync, readdirSync } from "node:fs"; import { homedir } from "node:os";
import { verifyObject, idOf } from "../packages/orbital-attest/verify.mjs";
const pwDir = `${homedir()}/.cache/ms-playwright`; const pw = existsSync(pwDir) ? readdirSync(pwDir).filter((d) => d.startsWith("chromium-")).sort().map((d) => `${pwDir}/${d}/chrome-linux64/chrome`).filter(existsSync).pop() : null;
const CHROME = process.env.CHROME || pw || "chromium"; const base = process.argv[2] || "http://localhost:8100"; const port = 9500 + Math.floor(Math.random() * 100);
const chrome = spawn(CHROME, ["--headless=new", "--no-sandbox", "--disable-gpu", `--remote-debugging-port=${port}`, "--user-data-dir=/tmp/attest-e2e-" + port, "about:blank"], { stdio: "ignore" });
for (let i = 0; i < 40; i++) { try { await fetch(`http://127.0.0.1:${port}/json/version`); break; } catch { await new Promise((r) => setTimeout(r, 250)); } }
const page = (await (await fetch(`http://127.0.0.1:${port}/json`)).json()).find((t) => t.type === "page"); const ws = new WebSocket(page.webSocketDebuggerUrl); await new Promise((r) => ws.on("open", r)); let id = 0;
const send = (method, params = {}) => new Promise((res, rej) => { const i = ++id; const h = (m) => { const j = JSON.parse(m); if (j.id === i) { ws.off("message", h); j.error ? rej(new Error(j.error.message)) : res(j.result); } }; ws.on("message", h); ws.send(JSON.stringify({ id: i, method, params })); });
ws.on("message", (m) => { const j = JSON.parse(m); if (j.method === "Runtime.exceptionThrown") console.error("  EXCEPTION", j.params.exceptionDetails.exception?.description?.split("\n")[0]); if (j.method === "Runtime.consoleAPICalled" && j.params.type === "error") console.error("  console.error", j.params.args.map((a) => a.value || a.description).join(" ")); });
const evaluate = async (expression) => { const r = await send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description || "eval failed"); return r.result.value; };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); let fails = 0; const ok = (cond, msg) => { console.log(cond ? "  ✓" : "  ✗", msg); if (!cond) fails++; };
const go = async (path, ms = 1500) => { await send("Page.navigate", { url: base + path }); await sleep(ms); };
const waitFor = async (expr, ms = 8000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if (await evaluate(expr)) return true; await sleep(200); } return false; };
await send("Runtime.enable"); await send("Page.enable"); await send("WebAuthn.enable", { enableUI: false });
const { authenticatorId } = await send("WebAuthn.addVirtualAuthenticator", { options: { protocol: "ctap2", transport: "internal", hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
const handle = "e2e" + Math.random().toString(36).slice(2, 7);
console.log("register", handle);
await go("/login?return=/demo");
await evaluate(`document.getElementById('handle').value = ${JSON.stringify(handle)}; document.getElementById('register').click(); true`);
ok(await waitFor(`location.pathname === '/demo'`), "registered, delegated, redirected to /demo");
const creds = await send("WebAuthn.getCredentials", { authenticatorId }); ok(creds.credentials.length === 1, `virtual authenticator holds ${creds.credentials.length} credential`);
await sleep(1500);
ok(await evaluate(`!!localStorage.getItem('attest:session')`), "session stored");
ok(await evaluate(`document.body.innerText.includes('@' + ${JSON.stringify(handle)})`), "widget shows the handle");
console.log("upvote");
await evaluate(`document.querySelector('[data-attest] .up').click(); true`);
ok(await waitFor(`document.querySelector('[data-attest] .up').getAttribute('aria-pressed') === 'true' && document.querySelector('[data-attest] .n').textContent === '1'`), "upvote counted and marked mine");
console.log("comment");
await evaluate(`const ta = document.querySelector('[data-attest] textarea'); ta.value = 'signed hello from e2e'; document.querySelector('[data-attest] form button').click(); true`);
ok(await waitFor(`document.querySelector('[data-attest] li')?.innerText.includes('signed hello from e2e')`), "comment appears, attributed");
console.log("reload keeps state");
await go("/demo", 2500);
ok(await evaluate(`document.querySelector('[data-attest] .up').getAttribute('aria-pressed') === 'true' && document.querySelector('[data-attest] .n').textContent === '1'`), "after reload the upvote is still mine");
console.log("retract");
await evaluate(`document.querySelector('[data-attest] .up').click(); true`);
ok(await waitFor(`document.querySelector('[data-attest] .up').getAttribute('aria-pressed') === 'false' && document.querySelector('[data-attest] .n').textContent === '0'`), "retract drops the count to 0");
console.log("second widget, live push");
await evaluate(`document.querySelectorAll('[data-attest] .up')[1].click(); true`);
ok(await waitFor(`document.querySelectorAll('[data-attest] .n')[1].textContent === '1'`), "second target upvoted");
console.log("sign out, sign in again");
await evaluate(`localStorage.removeItem('attest:session'); true`); await go("/login?return=/me");
await evaluate(`document.getElementById('handle').value = ${JSON.stringify(handle)}; document.getElementById('signin').click(); true`);
ok(await waitFor(`location.pathname === '/me'`), "signed in again with the passkey");
await sleep(1200); const rows = await evaluate(`document.querySelectorAll('tbody tr').length`); ok(rows >= 4, `/me lists ${rows} records (upvote, comment, retract, upvote)`);
console.log("revoke this browser's session");
await go("/me", 2500);
ok(await evaluate(`!document.getElementById('own').hidden && document.querySelectorAll('#sessions tbody tr').length >= 1`), "own page shows sessions and passkeys");
const before = await evaluate(`localStorage.getItem('attest:session')`);
await evaluate(`document.querySelector('#sessions [data-revoke]').click(); true`);
ok(await waitFor(`!localStorage.getItem('attest:session')`), "revoking this session clears it locally");
await evaluate(`localStorage.setItem('attest:session', ${JSON.stringify("PLACEHOLDER")}); true`.replace('"PLACEHOLDER"', JSON.stringify(before)));
const afterRevoke = await evaluate(`(async () => { const A = await import('/attest-core.js'); try { await A.attest('upvote', 'https://example.org/after-revoke'); return 'accepted'; } catch (e) { return e.message; } })()`);
ok(/revoked/.test(afterRevoke), "a revoked delegation is refused server-side: " + afterRevoke);
await go("/login?return=/me");
await evaluate(`document.getElementById('handle').value = ${JSON.stringify(handle)}; document.getElementById('signin').click(); true`);
ok(await waitFor(`location.pathname === '/me'`), "signed in again after revocation (new delegation)");
console.log("second passkey (a second virtual authenticator, as a second device would be)");
await send("WebAuthn.addVirtualAuthenticator", { options: { protocol: "ctap2", transport: "usb", hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
await sleep(1500); await evaluate(`document.getElementById('addkey').click(); true`);
ok(await waitFor(`document.getElementById('keymsg').textContent.startsWith('Added. You have 2')`, 15000), "second passkey added, approved by the first: " + await evaluate(`document.getElementById('keymsg').textContent`));
const keysNow = (await (await fetch(base + "/by/" + encodeURIComponent(await evaluate(`JSON.parse(localStorage.getItem('attest:session')).root`)))).json()).keys.length; ok(keysNow === 2, `account now lists ${keysNow} passkeys`);
await evaluate(`document.querySelector('#keys [data-remove]').click(); true`);
ok(await waitFor(`document.getElementById('keymsg').textContent.startsWith('Passkey removed') || document.getElementById('keymsg').className.includes('err')`, 15000), "remove a passkey: " + await evaluate(`document.getElementById('keymsg').textContent`));
console.log("bad record is refused");
const refused = await evaluate(`(async () => { const A = await import('/attest-core.js'); const env = await A.makeRecord('upvote', 'https://example.org/x'); env.record.body = 'tampered'; try { await A.req('attest', env); return 'accepted'; } catch (e) { return e.message; } })()`);
ok(/signature does not verify|unexpected|body/.test(refused), "tampered record refused: " + refused);
console.log("offline verification");
const did = await evaluate(`JSON.parse(localStorage.getItem('attest:session')).root`);
const me = await (await fetch(`${base}/by/${encodeURIComponent(did)}`)).json(); const comment = me.records.find((r) => r.kind === "comment");
const rec = await (await fetch(`${base}/record/${comment.id}`)).json(); const del = (await (await fetch(`${base}/log?since=0`)).json()).entries.find((e) => e.type === "delegation" && e.id === rec.del);
ok((await idOf(rec.record)) === comment.id, "record id is the sha256 of its canonical form");
ok(await verifyObject(del.delegation.devKey, rec.record, rec.sig), "device-key signature verifies from the log alone");
ok(del.delegation.root === did && me.keys.length === 1, "delegation root is the account; root key is published for checking the passkey assertion");
console.log(fails ? `${fails} FAILED` : "all passed");
ws.close(); chrome.kill(); process.exit(fails ? 1 : 0);
